### PR TITLE
Add support for X509Certificate2 that uses the Cryptography API: Next Generation (CNG)

### PR DESCRIPTION
**Pull request by huan086**
When an X509Certificate2 is created using CNG instead of Cryptographic Application Programming Interface (CAPI), accessing the PrivateKey property of the X509Certificate2 will cause an exception.

This commit uses the CLR Security https://clrsecurity.codeplex.com/, which provides a wrapper around CNG Windows API and exposes an extension method for to get the CNG private key.

### CODE REVIEW

**Comment by Snede** [comment]
We just implemented this into our production environment. Nice work.

**Comment by huan086** [comment]
@Snede, please update to the latest version with XXE vulnerability fixes

**Comment by starteleport** [comment]
Hello! I've noticed 5 open PRs, and it seems to me that this repo is not actively maintained. I would like to make use of SAML SSO in my app and stick to some alive fork, both to ask questions and make PRs, if I have an opportunity. Is there anyone who still maintains this package?

**Comment by huan086** [comment]
@starteleport: the code works, and if you want CNG support for the relying party, use my fork.

If you want CNG support for identity provider, sadly I don't see any fork that worked on that

**Comment by Revsgaard** [comment]
I'm working on a big update of the ITfoxtec.SAML2 component. Which will have .NET nativaly support for SHA256, be able to work both as Identity Provider and Relying Party and support ASP.NET 5 MVC 6 (no referances to System.Web).

**Comment by Revsgaard** [comment]
Closing because this component is discontinued, it has a number of problems and some security issues. Therefor, please use the new [ITfoxtec Identity Saml2](https://www.itfoxtec.com/identitysaml2) component instead.

**Pull request closed without merging**
